### ISSUE TITLE
How can I alter the coq load path? 

### ISSUE THREAD

**Issue by langston-barrett** [olivierverdier/spacemacs-coq#11]
I'm using this layer, and I'd like to edit the Proof General variable [`coq-load-path`](http://proofgeneral.inf.ed.ac.uk/htmlshow.php?title=Proof+General+user+manual&file=releases%2FProofGeneral%2Fdoc%2FProofGeneral%2FProofGeneral_12.html). What's the best way to go about this?

**Comment by olivierverdier** [comment]
This is not covered by this layer. You should customize that variable in spacemacs. If you think that it would be a valuable addition to this layer (I think it could, if you want to use other coq implementations, for instance [`hoq`](https://github.com/HoTT/HoTT)), please submit a pull request.

**Comment by langston-barrett** [comment]
@olivierverdier Thanks for the clarification! Do you know where/how I should add it to my `.spacemacs`? The configuration organization still confuses me... Sorry for the simple question.
