### ISSUE TITLE
company-coq doesn't work properly

### ISSUE THREAD

**Issue by jinyangustc** [olivierverdier/spacemacs-coq#2]
Hi, thank you for sharing your coq config. It is really nice. However, I encounter some problems with the completion, i.e. company-coq-mode. I thought it is something with the `company-coq-mode` and I find a similar issue at https://github.com/cpitclaudel/company-coq/issues/79. Do you encounter similar problems? Is it something about our Spacemacs configuration or about `company-coq-mode`? Thank you again!

**Comment by olivierverdier** [comment]
This should be fixed by PR #5. Feel free to reopen if not.
