### ISSUE TITLE
Default color scheme is jarring

### ISSUE THREAD

**Issue by kandersen** [olivierverdier/spacemacs-coq#3]
The default colors used by the combination of Proof General + Spacemacs and the default scheme of the latter clashes awfully in the "response" buffer. To wit, a screenshot of a (to my eyes) unusable turquoise-on-orange:
<img width="840" alt="screen shot 2016-06-28 at 13 45 15" src="https://cloud.githubusercontent.com/assets/1170540/16414234/ceb24f56-3d36-11e6-96c8-cc9f9151f575.png">

Can we do something sensible about the default colors? Perhaps the orange background of the error message is overkill?

**Comment by olivierverdier** [comment]
Good point. I already noticed the problem and changed the Coq colours in my general preferences. Probably a good idea to add them to the layer.

**Comment by kandersen** [comment]
👍

**Comment by kandersen** [comment]
Brilliant, will check it out!
